/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Multicall__factory } from "./Multicall__factory";
export { UniversalErc1155__factory } from "./UniversalErc1155__factory";
export { UniversalErc20__factory } from "./UniversalErc20__factory";
export { UniversalErc721__factory } from "./UniversalErc721__factory";
